### ISSUE TITLE
Does this library support dialog fragment as well?

### ISSUE THREAD

**Issue by mochadwi** [hoc081098/ViewBindingDelegate#2]
We're using https://github.com/kirich1409/ViewBindingPropertyDelegate currently, is there any milestone to support dialog fragment @hoc081098?

Or maybe what's the difference about your library and @kirich1409 you both using reflection & reflectionless approach

**Comment by kirich1409** [comment]
The library has support of `DialogFragment` or I need more information about what you need in that kind of support

**Comment by hoc081098** [comment]
Hi @mochadwi, see https://github.com/hoc081098/ViewBindingDelegate/releases/tag/1.0.0-alpha02
