### ISSUE TITLE
Tricky bug when a Fragment is added as detached

### ISSUE THREAD

**Issue by Zhuinden** [hoc081098/ViewBindingDelegate#5]
https://github.com/hoc081098/ViewBindingDelegate/blob/0e8139a64267b73a55c9dfa2b384b5959fc2bf6d/library/src/main/java/com/hoc081098/viewbindingdelegate/impl/FragmentViewBindingDelegate.kt#L69

See https://twitter.com/Zhuinden/status/1351626498252402688

Apparently Fragment viewLifecycle does not always works as intended, and just checking if the binding exists is not enough, it must also be checked if the binding view is valid.

**Comment by hoc081098** [comment]
Thanks.
